# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cientifica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.pushButtonDigito1 = QtWidgets.QPushButton(Dialog)
        self.pushButtonDigito1.setGeometry(QtCore.QRect(130, 120, 75, 23))
        self.pushButtonDigito1.setStyleSheet(" background-color: #007BFF;\n"
" color: white;\n"
" border: none;\n"
" border-radius: 10px;\n"
" padding: 6px 12px;")
        self.pushButtonDigito1.setObjectName("pushButtonDigito1")
        self.pushButtonDigito2 = QtWidgets.QPushButton(Dialog)
        self.pushButtonDigito2.setGeometry(QtCore.QRect(130, 150, 75, 23))
        self.pushButtonDigito2.setObjectName("pushButtonDigito2")
        self.pushButtonVoltar = QtWidgets.QPushButton(Dialog)
        self.pushButtonVoltar.setGeometry(QtCore.QRect(10, 270, 75, 23))
        self.pushButtonVoltar.setObjectName("pushButtonVoltar")
        self.lineEdit_3 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 10, 269, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.displayUser = QtWidgets.QLineEdit(Dialog)
        self.displayUser.setGeometry(QtCore.QRect(110, 80, 113, 20))
        self.displayUser.setReadOnly(True)
        self.displayUser.setObjectName("displayUser")
        self.pushButtonDigito3 = QtWidgets.QPushButton(Dialog)
        self.pushButtonDigito3.setGeometry(QtCore.QRect(130, 180, 75, 23))
        self.pushButtonDigito3.setObjectName("pushButtonDigito3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonDigito1.setText(_translate("Dialog", "1"))
        self.pushButtonDigito2.setText(_translate("Dialog", "2"))
        self.pushButtonVoltar.setText(_translate("Dialog", "Voltar"))
        self.lineEdit_3.setText(_translate("Dialog", "Cientifica"))
        self.pushButtonDigito3.setText(_translate("Dialog", "3"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
