# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'normal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(312, 434)
        Dialog.setStyleSheet("QWidget {\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #f3e7d3,   /* milk foam */\n"
"        stop: 1 #d9c3a5    /* latte base */\n"
"    );\n"
"}")
        self.pushButtonVoltar = QtWidgets.QPushButton(Dialog)
        self.pushButtonVoltar.setGeometry(QtCore.QRect(200, 40, 81, 31))
        self.pushButtonVoltar.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #7f8a95,   /* soft steel highlight */\n"
"        stop: 1 #4f5963    /* deep cool gray */\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #6a7682;\n"
"\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Montserrat\", \"Segoe UI Variable\", \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"\n"
"    letter-spacing: 0.3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #8d98a3,\n"
"        stop: 1 #5a6671\n"
"    );\n"
"\n"
"    border: 1px solid #7b8793;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #3e4750;\n"
"\n"
"    border: 1px solid #9aa6b2;\n"
"\n"
"    padding-top: 9px;\n"
"    padding-left: 15px;\n"
"}")
        self.pushButtonVoltar.setObjectName("pushButtonVoltar")
        self.lineTextNormal = QtWidgets.QLineEdit(Dialog)
        self.lineTextNormal.setEnabled(False)
        self.lineTextNormal.setGeometry(QtCore.QRect(30, 40, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.lineTextNormal.setFont(font)
        self.lineTextNormal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineTextNormal.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #d07a2f,\n"
"        stop: 1 #9b4f16\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #b86a22;\n"
"\n"
"    border-radius: 8px;\n"
"\n"
"    padding: 6px 10px;\n"
"\n"
"     font-family: \"Montserrat\", \"Segoe UI Variable\", \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"\n"
"    letter-spacing: 1.2px;\n"
"\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.lineTextNormal.setReadOnly(False)
        self.lineTextNormal.setObjectName("lineTextNormal")
        self.displayUser = QtWidgets.QLineEdit(Dialog)
        self.displayUser.setGeometry(QtCore.QRect(30, 80, 251, 41))
        self.displayUser.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #e6e2dc,   /* warm light gray */\n"
"        stop: 1 #d2ccc4    /* slightly deeper warm gray */\n"
"    );\n"
"\n"
"    color: #1e1b18;      /* dark warm charcoal */\n"
"\n"
"    border: 1px solid #b8b1a8;\n"
"\n"
"    border-radius: 8px;\n"
"\n"
"    padding: 10px 12px;\n"
"\n"
"    font-family: \"Consolas\";\n"
"    font-size: 24px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.5px;\n"
"\n"
"    qproperty-alignment: \'AlignRight | AlignVCenter\';\n"
"}")
        self.displayUser.setReadOnly(True)
        self.displayUser.setObjectName("displayUser")
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 130, 251, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonDigitoN8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN8.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN8.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN8.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN8.setObjectName("pushButtonDigitoN8")
        self.gridLayout.addWidget(self.pushButtonDigitoN8, 1, 1, 1, 1)
        self.pushButtonDigitoN9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN9.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN9.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN9.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN9.setObjectName("pushButtonDigitoN9")
        self.gridLayout.addWidget(self.pushButtonDigitoN9, 1, 2, 1, 1)
        self.pushButtonOPN_MUL = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOPN_MUL.sizePolicy().hasHeightForWidth())
        self.pushButtonOPN_MUL.setSizePolicy(sizePolicy)
        self.pushButtonOPN_MUL.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #7a6f66,   /* warm gray-brown highlight */\n"
"        stop: 1 #4b423c    /* darker warm base */\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #8a7f76;\n"
"\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"\n"
"    letter-spacing: 0.3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #8a7f75,\n"
"        stop: 1 #5a4f47\n"
"    );\n"
"\n"
"    border: 1px solid #9b8f85;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #3e3530;\n"
"\n"
"    border: 1px solid #b8a89b;\n"
"\n"
"    padding-top: 9px;\n"
"    padding-left: 15px;\n"
"}")
        self.pushButtonOPN_MUL.setObjectName("pushButtonOPN_MUL")
        self.gridLayout.addWidget(self.pushButtonOPN_MUL, 2, 3, 1, 1)
        self.pushButtonN_DOT = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonN_DOT.sizePolicy().hasHeightForWidth())
        self.pushButtonN_DOT.setSizePolicy(sizePolicy)
        self.pushButtonN_DOT.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonN_DOT.setObjectName("pushButtonN_DOT")
        self.gridLayout.addWidget(self.pushButtonN_DOT, 4, 1, 1, 1)
        self.pushButtonDigitoN3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN3.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN3.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN3.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN3.setObjectName("pushButtonDigitoN3")
        self.gridLayout.addWidget(self.pushButtonDigitoN3, 3, 0, 1, 1)
        self.pushButtonDigitoN1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN1.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN1.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN1.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN1.setObjectName("pushButtonDigitoN1")
        self.gridLayout.addWidget(self.pushButtonDigitoN1, 3, 2, 1, 1)
        self.pushButtonDigitoN5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN5.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN5.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN5.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN5.setObjectName("pushButtonDigitoN5")
        self.gridLayout.addWidget(self.pushButtonDigitoN5, 2, 1, 1, 1)
        self.pushButtonDigitoN2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN2.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN2.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN2.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN2.setObjectName("pushButtonDigitoN2")
        self.gridLayout.addWidget(self.pushButtonDigitoN2, 3, 1, 1, 1)
        self.pushButtonOPN_EQU = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOPN_EQU.sizePolicy().hasHeightForWidth())
        self.pushButtonOPN_EQU.setSizePolicy(sizePolicy)
        self.pushButtonOPN_EQU.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #7a6f66,   /* warm gray-brown highlight */\n"
"        stop: 1 #4b423c    /* darker warm base */\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #8a7f76;\n"
"\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"\n"
"    letter-spacing: 0.3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #8a7f75,\n"
"        stop: 1 #5a4f47\n"
"    );\n"
"\n"
"    border: 1px solid #9b8f85;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #3e3530;\n"
"\n"
"    border: 1px solid #b8a89b;\n"
"\n"
"    padding-top: 9px;\n"
"    padding-left: 15px;\n"
"}")
        self.pushButtonOPN_EQU.setObjectName("pushButtonOPN_EQU")
        self.gridLayout.addWidget(self.pushButtonOPN_EQU, 4, 2, 1, 1)
        self.pushButtonOPN_ADD = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOPN_ADD.sizePolicy().hasHeightForWidth())
        self.pushButtonOPN_ADD.setSizePolicy(sizePolicy)
        self.pushButtonOPN_ADD.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #7a6f66,   /* warm gray-brown highlight */\n"
"        stop: 1 #4b423c    /* darker warm base */\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #8a7f76;\n"
"\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"\n"
"    letter-spacing: 0.3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #8a7f75,\n"
"        stop: 1 #5a4f47\n"
"    );\n"
"\n"
"    border: 1px solid #9b8f85;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #3e3530;\n"
"\n"
"    border: 1px solid #b8a89b;\n"
"\n"
"    padding-top: 9px;\n"
"    padding-left: 15px;\n"
"}")
        self.pushButtonOPN_ADD.setObjectName("pushButtonOPN_ADD")
        self.gridLayout.addWidget(self.pushButtonOPN_ADD, 4, 3, 1, 1)
        self.pushButtonDigitoN4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN4.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN4.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN4.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN4.setObjectName("pushButtonDigitoN4")
        self.gridLayout.addWidget(self.pushButtonDigitoN4, 2, 0, 1, 1)
        self.pushButtonDigitoN7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN7.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN7.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN7.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN7.setObjectName("pushButtonDigitoN7")
        self.gridLayout.addWidget(self.pushButtonDigitoN7, 1, 0, 1, 1)
        self.pushButtonDigitoN6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN6.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN6.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN6.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN6.setObjectName("pushButtonDigitoN6")
        self.gridLayout.addWidget(self.pushButtonDigitoN6, 2, 2, 1, 1)
        self.pushButtonDigitoN0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDigitoN0.sizePolicy().hasHeightForWidth())
        self.pushButtonDigitoN0.setSizePolicy(sizePolicy)
        self.pushButtonDigitoN0.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #505050,\n"
"        stop: 1 #2a2a2a\n"
"    );\n"
"\n"
"    color: #ffffff;   /* pure white */\n"
"\n"
"    border: 1px solid #6a6a6a;\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 500;\n"
"\n"
"    letter-spacing: 0.4px;\n"
"}")
        self.pushButtonDigitoN0.setObjectName("pushButtonDigitoN0")
        self.gridLayout.addWidget(self.pushButtonDigitoN0, 4, 0, 1, 1)
        self.pushButtonOPN_SUB = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOPN_SUB.sizePolicy().hasHeightForWidth())
        self.pushButtonOPN_SUB.setSizePolicy(sizePolicy)
        self.pushButtonOPN_SUB.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #7a6f66,   /* warm gray-brown highlight */\n"
"        stop: 1 #4b423c    /* darker warm base */\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #8a7f76;\n"
"\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"\n"
"    letter-spacing: 0.3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #8a7f75,\n"
"        stop: 1 #5a4f47\n"
"    );\n"
"\n"
"    border: 1px solid #9b8f85;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #3e3530;\n"
"\n"
"    border: 1px solid #b8a89b;\n"
"\n"
"    padding-top: 9px;\n"
"    padding-left: 15px;\n"
"}")
        self.pushButtonOPN_SUB.setObjectName("pushButtonOPN_SUB")
        self.gridLayout.addWidget(self.pushButtonOPN_SUB, 3, 3, 1, 1)
        self.pushButtonOPN_DIV = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonOPN_DIV.sizePolicy().hasHeightForWidth())
        self.pushButtonOPN_DIV.setSizePolicy(sizePolicy)
        self.pushButtonOPN_DIV.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #7a6f66,   /* warm gray-brown highlight */\n"
"        stop: 1 #4b423c    /* darker warm base */\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #8a7f76;\n"
"\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"\n"
"    letter-spacing: 0.3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #8a7f75,\n"
"        stop: 1 #5a4f47\n"
"    );\n"
"\n"
"    border: 1px solid #9b8f85;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #3e3530;\n"
"\n"
"    border: 1px solid #b8a89b;\n"
"\n"
"    padding-top: 9px;\n"
"    padding-left: 15px;\n"
"}")
        self.pushButtonOPN_DIV.setObjectName("pushButtonOPN_DIV")
        self.gridLayout.addWidget(self.pushButtonOPN_DIV, 1, 3, 1, 1)
        self.pushButtonN_Clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonN_Clear.sizePolicy().hasHeightForWidth())
        self.pushButtonN_Clear.setSizePolicy(sizePolicy)
        self.pushButtonN_Clear.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #d07a2f,   /* warm orange highlight */\n"
"        stop: 1 #9b4f16    /* deep burnt orange */\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #b86a22;\n"
"\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI Variable\", \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #e0893a,\n"
"        stop: 1 #a8561a\n"
"    );\n"
"\n"
"    border: 1px solid #cc7a2a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #7f3e10;\n"
"\n"
"    border: 1px solid #f0a24a;\n"
"\n"
"    padding-top: 9px;\n"
"    padding-left: 15px;\n"
"}")
        self.pushButtonN_Clear.setObjectName("pushButtonN_Clear")
        self.gridLayout.addWidget(self.pushButtonN_Clear, 0, 0, 1, 1)
        self.pushButtonN_ANS = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonN_ANS.sizePolicy().hasHeightForWidth())
        self.pushButtonN_ANS.setSizePolicy(sizePolicy)
        self.pushButtonN_ANS.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #d07a2f,   /* warm orange highlight */\n"
"        stop: 1 #9b4f16    /* deep burnt orange */\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #b86a22;\n"
"\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Segoe UI Variable\", \"Segoe UI\";\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    letter-spacing: 0.3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #e0893a,\n"
"        stop: 1 #a8561a\n"
"    );\n"
"\n"
"    border: 1px solid #cc7a2a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #7f3e10;\n"
"\n"
"    border: 1px solid #f0a24a;\n"
"\n"
"    padding-top: 9px;\n"
"    padding-left: 15px;\n"
"}")
        self.pushButtonN_ANS.setObjectName("pushButtonN_ANS")
        self.gridLayout.addWidget(self.pushButtonN_ANS, 0, 1, 1, 1)
        self.pushButtonN_BACK = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonN_BACK.sizePolicy().hasHeightForWidth())
        self.pushButtonN_BACK.setSizePolicy(sizePolicy)
        self.pushButtonN_BACK.setStyleSheet("QPushButton {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #7f8a95,\n"
"        stop: 1 #4f5963\n"
"    );\n"
"\n"
"    color: #ffffff;\n"
"\n"
"    border: 1px solid #6a7682;\n"
"\n"
"    border-radius: 9px;\n"
"\n"
"    padding: 8px 14px;\n"
"\n"
"    font-family: \"Montserrat\", \"Segoe UI Variable\", \"Segoe UI\";\n"
"    font-size: 15px;\n"
"    font-weight: 600;\n"
"\n"
"    letter-spacing: 0.3px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"\n"
"    background-color: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #8d98a3,\n"
"        stop: 1 #5a6671\n"
"    );\n"
"\n"
"    border: 1px solid #7b8793;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"\n"
"    background-color: #3e4750;\n"
"\n"
"    border: 1px solid #9aa6b2;\n"
"\n"
"    padding-top: 9px;\n"
"    padding-left: 15px;\n"
"}")
        self.pushButtonN_BACK.setObjectName("pushButtonN_BACK")
        self.gridLayout.addWidget(self.pushButtonN_BACK, 0, 3, 1, 1)
        self.gridLayout.setRowMinimumHeight(0, 1)
        self.gridLayout.setRowMinimumHeight(1, 1)
        self.gridLayout.setRowMinimumHeight(2, 1)
        self.gridLayout.setRowMinimumHeight(3, 1)
        self.gridLayout.setRowMinimumHeight(4, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.gridLayout.setRowStretch(3, 1)
        self.gridLayout.setRowStretch(4, 1)
        self.lineTextTitle = QtWidgets.QLineEdit(Dialog)
        self.lineTextTitle.setGeometry(QtCore.QRect(10, 0, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(88)
        self.lineTextTitle.setFont(font)
        self.lineTextTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineTextTitle.setStyleSheet("QLineEdit {\n"
"\n"
"    background-color: transparent;\n"
"\n"
"    color: #2f1f17;   /* dark coffee text */\n"
"\n"
"    border: none;\n"
"\n"
"    padding: 4px 0px;\n"
"\n"
"    font-family: \"Montserrat\", \"Segoe UI Variable\", \"Segoe UI\";\n"
"    font-size: 18px;\n"
"    font-weight: 700;\n"
"\n"
"    letter-spacing: 2px;\n"
"\n"
"    qproperty-alignment: \'AlignCenter\';\n"
"}")
        self.lineTextTitle.setReadOnly(False)
        self.lineTextTitle.setObjectName("lineTextTitle")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButtonVoltar.setText(_translate("Dialog", "Voltar"))
        self.lineTextNormal.setText(_translate("Dialog", "Normal"))
        self.displayUser.setText(_translate("Dialog", "1234567890"))
        self.pushButtonDigitoN8.setText(_translate("Dialog", "8"))
        self.pushButtonDigitoN9.setText(_translate("Dialog", "9"))
        self.pushButtonOPN_MUL.setText(_translate("Dialog", "X"))
        self.pushButtonN_DOT.setText(_translate("Dialog", "."))
        self.pushButtonDigitoN3.setText(_translate("Dialog", "3"))
        self.pushButtonDigitoN1.setText(_translate("Dialog", "1"))
        self.pushButtonDigitoN5.setText(_translate("Dialog", "5"))
        self.pushButtonDigitoN2.setText(_translate("Dialog", "2"))
        self.pushButtonOPN_EQU.setText(_translate("Dialog", "="))
        self.pushButtonOPN_ADD.setText(_translate("Dialog", "+"))
        self.pushButtonDigitoN4.setText(_translate("Dialog", "4"))
        self.pushButtonDigitoN7.setText(_translate("Dialog", "7"))
        self.pushButtonDigitoN6.setText(_translate("Dialog", "6"))
        self.pushButtonDigitoN0.setText(_translate("Dialog", "0"))
        self.pushButtonOPN_SUB.setText(_translate("Dialog", "-"))
        self.pushButtonOPN_DIV.setText(_translate("Dialog", "/"))
        self.pushButtonN_Clear.setText(_translate("Dialog", "C"))
        self.pushButtonN_ANS.setText(_translate("Dialog", "ANS"))
        self.pushButtonN_BACK.setText(_translate("Dialog", "⌫"))
        self.lineTextTitle.setText(_translate("Dialog", "☕ COFFEE CALCULATOR ☕"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
